Project to keep my notes organized for "Cataclysm: Dark Days Ahead" (C:DDA) development

* Documentation Contents
  - [[file:buildTestVersion.org][Build Test Version]]

* In-Repo Project Documentation
  - [[file:src/cdda/.github/CONTRIBUTING.md][Contribute]] guidelines
  - [[file:src/cdda/doc/CODE_STYLE.md][Code Style Guide]]

* Other useful C:DDA links
  - [[https://cataclysmdda.org/][Main site]] - Generated using [[file:src/cdda-gh-pages/][GitHub Pages]]
  - [[https://github.com/CleverRaven/Cataclysm-DDA][Offical Repository]]
    - [[https://github.com/CleverRaven/Cataclysm-DDA/issues?q=is%3Aissue+sort%3Aupdated-desc+][Recently Updated Issues]]
    - [[https://github.com/CleverRaven/Cataclysm-DDA/pulls?q=is%3Apr+sort%3Aupdated-desc][Recently Updated Pull Requests]]
 - Development discussion is done on the "Cataclysm: Dark Days Ahead" [[https://discord.com][Discord Server]]
* Organization
** Directory Structure
  - README.org - This file
  - [[file://issues/][issues/]]    - Notes on investigation of issue     
  - src/
    - cdda/    - ~git subtree~ of C:DDA master branch
    - cdda-gh-pages/ - ~git subtree~ of C:DDA gh-pages branch
** Branch Names
   - main         - The main working branch	 
   - upstream-*   - Branches holding fetches from the main project
   - pr-*       - Branches that will be submitted upstream as a pull request
   - wip-*        - Branches that are unstable. **Warning** may be rebased
   - remotes/     - On dev machine remote pointing to github
     - upstream/
       - master   - Tracks master branch on "CleverRaven / Cataclysm-DDA"
       - gh-pages - Tracks gh-pages brach on "CleverRaven / Cataclysm-DDA"
     - github/
       - main     - Tracks my main working branch on github

** GitHub
   Project development coordination is done on GitHub.  Structure supports
   pull requests like the rest of the developers.
*** [[https://github.com/CleverRaven/Cataclysm-DDA][CleverRaven / Cataclysm-DDA]]
    - Official Repository used by developers
    - Branches we care about: master, gh-pages
*** [[https://github.com/ghiknt/contrib-cdda-fork][ghiknt / contrib-cdda-fork]]
    - Fork of "CleverRaven / Cataclysm-DDA" Master Branch
    - Pull requests will be submited from branches here
*** [[https://github.com/ghiknt/contrib-cdda][ghiknt / contrib-cdda]]
    - Fork of "CleverRaven / Cataclysm-DDA"
      - master renamed to upstream-master
      - gh-pages renamed to upstream-gh-pages
      - 0-F-branch renamed to upstream-0-F-branch
      - All other forked branches deleted on github
    - main branch created with master & gh-pages as git subtree's
    - Pull requests will be submitted from pr-* branches

* git commands
** Creation
   
   #+begin_src shell
     # Initialization
     cd ~/src/contrib
     mkdir -p cdda/src
     cd cdda
     git init
     # README file addition
     git add README.org
     git commit -m "doc: Initial project creation and addition of README.org"

     # Add .gitignore using gitignore.io with ~emacs~ and ~c++~ as a base
     git add .gitignore
     git commit -m "feat(config): Initial gitignore file." \
	 -m "From https://www.toptal.com/developers/gitignore/api/emacs,c++." \
	 -m "SPDX-License-Identifier: MIT"

     # Rename master to main to fit current conventions
     git branch -m master main
     # Add remotes for main project and subtree
     git remote add github git@github.com:ghiknt/contrib-cdda.git
     git remote add upstream https://github.com/CleverRaven/Cataclysm-DDA.git

     # Push main project to github
     git push -u github main

     # Save changes to README.org so we have a clean repository to allow the subtree add
     git add README.org
     git commit -m "doc: Updates to README.org"

     # Add C:DDA main branch
     git subtree add --prefix src/cdda upstream master

     # Add C:DDA gh-pages branch
     git subtree add --prefix src/cdda-gh-pages upstream gh-pages

     # Create initial branches tracking the upstream branches created by subtree
     git branch --track upstream-master remotes/upstream/master
     git branch --track upstream-gh-pages remotes/upstream/gh-pages

     git push github upstream-master:upstream-master
     git push github upstream-gh-pages:upstream-gh-pages
     # Commit README.org with setup and then push it all back to github
     git add README.org
     git commit -m "doc: Initial configuration commands added"
     git push github main
   #+end_src

** Managing a topic branch

   #+begin_src shell
     # Make sure we are in sync with upstream
     git checkout main
     git subtree pull --prefix src/cdda upstream master
     git subtree pull --prefix src/cdda-gh-pages upstream gh-pages

     # Create and switch to  wip-* branch
     git branch wip-nameGoesHere
     git checkout wip-nameGoesHere
   #+end_src
   

* Commit notes
  - The project encourages use of [[https://www.conventionalcommits.org/en/v1.0.0/#specification][Conventional Commits]]
    - types I use
      - fix:   - per spec
      - feat:  - per spec
      - doc:   - documentation updates
      - wip:   - Commit to capture changes to in progress work.  Should be squashed out of submitted branches
  - Commits should be split between main project and subtrees in ./src/*    
